### ISSUE TITLE
Create ICard Admin website

### ISSUE THREAD

**Issue by jjjongyb** [UofA-Blueprint/issues#94]
As an ISA officer, I want to be able to manage the backend apps and mobile apps from a secured web app.

Stories:
- [x] #95 

Design: TBC

User problem: ISA officers want to be able to manage the ICard app but doesn't have safe and intuitive tools to do it.

User outcome:

- Hypothesis: with a safe and intuitive admin website, ISA officers can regularly update the app data ensuring up-to-date vendors' data and a smooth experience for the student registration process.
- Risks: ISA officers won't use the admin site regularly because of a learning curve and bad UX.

Personas:

- ISA officer: Once a week, I want to be able to log in to the admin website with my credentials, and verify the registration of ICard users. Occasionally, I need to add/update vendors' data and help students with any registration issues.

MVP: Login page, manage students' data, manage vendors' data

Enabler for: N/A

Dependence on:  #60 

Acceptance Criteria:

- [x] I need to be able to log in with credential(s) only known by ISA officers
- [x] I need to be able to manage the admin account(s) from the admin website
- [x] I need to be able to manage student's data:
  - [x] verify students' account
  - [x] update, delete, create, read student's data
- [x] I need to be able to create, read, update, delete vendors' data

Nonfunctional requirements:

- [x] the admin website needs to display and function properly on a desktop of all size
- [x] the admin website should be available 99% of the time

Environments: web

Architecture: TBC

Exclusion:

- integration with other admin system operated by ISA (e.g., for their website)
